### ISSUE TITLE
SVG?

### ISSUE THREAD

**Issue by ziriax** [wessberg/pointer-events#1]
Very nice initiative!

I tried your plugin on `iOS` Safari and the `pointer down` event fired on a `div`, but not on an SVG (loaded with `https://www.npmjs.com/package/react-svg`).

I added a `touch start` event on the SVG element, and that *is* fired.

Should your polyfill also work with SVG? 

Thanks,
Peter

**Comment by wessberg** [comment]
That's strange. Yes, this polyfill patches the `EventTarget` prototype and thus everything that extends from it (such as the `Node` interface and by extension `SVGElement` and `HTMLElement`). I would very much like to investigate this issue. Do you have a simple repro I can take a look at? Thanks for reporting this issue.

**Comment by ziriax** [comment]
I will try to make a codepen this week. Thanks for the fast reply!

**Comment by ziriax** [comment]
I think I'm just doing something wrong on `iOS`, because the pointer-down event on a `div` is raised after installing your package, but the `onpointermove` or `onpointerup` events are not handled. Also, iOS seems to handle the touch events itself, because it is panning the viewport.

I basically just want to handle `onpointerdown`, `onpointermove` and `onpointerup` myself, overriding any default behavior. Typically I do this by adding `ontouchstart` etc on mobile, called `preventDefault`, but I wanted to give your polyfill a try.

Maybe I should not use your polyfill if all I want to completely override the default behaviors? I had the idea I had to use `touchAction: none` for this?

**Comment by wessberg** [comment]
You're definitely on to something regarding `touchAction`.
By default, scrolling and other gestures are handled exclusively by the browser.

In the past, with Touch Events, you could be scrolling a page *while* tracking a sequence of Touch Events such as `touchstart`/`touchmove`/`touchend`, often resulting in somewhat messy behavior when you are trying to support, say, swiping some content, but the page is scrolling at the same time.

PointerEvents improve on this situation, but it also leads to some gotchas.
With PointerEvents, as soon as the browser detects a touch gesture, (such as panning in any scrollable axis), it fires a `pointercancel` event on the element that is listening for Pointer Events. From what you are saying, it sounds a lot like that is what you are running into:

- A `pointerdown` event is fired.
- You start dragging your finger around, expecting `pointermove` events, however:
- The browser fires a `pointercancel` event on the element since it detects a touch gesture that could lead to things like scrolling the page.

All this to say: If you set `touch-action: none` as a style attribute (or `style.touchAction = "none"` on the element imperatively) it should work. Because you're saying to the browser: _"Hey, when a sequence of Pointer Events are active on this element, I don't want you, the browser, to handle any touch gestures - I'm using them for something right now"_.
